Make FeedSpider 2 a PWA
OthelloVenturesLtd/FeedSpider2 pull request #9
Opened 2022-11-13 21:25 UTC by codepoet80

The following changes allow FeedSpider to work as a modern Progress Web App (PWA) on iOS, Android and Chrome...

- Bumped version, added manifest.json and stub service worker. Added appropriate icon references in manifest and index.html. Added metatags for use on iOS.
- Added stub serviceworker so Chrome will offer the "Install" option
- Moved InoReader to a (now public) nginx reverse proxy to allow CORS, so that it will load on a modern browser. Other back-ends not yet supported (except on older devices that don't care about CORS). Example nginx config file included.
- Other back-ends to be supported in future PRs.

Try it out at [https://feedspider.online/app](https://feedspider.online/app)

2022-11-16 19:17 UTC, OthelloVentures requested changes

2022-11-16 19:17 UTC, OthelloVentures commented on enyo-app/index.html
> +					console.log('ServiceWorker registration failed: ', err);
console.log should be avoided in the production app

2022-11-16 19:17 UTC, OthelloVentures commented on enyo-app/index.html
> +				console.log("touchstart");
As above

2022-11-16 19:17 UTC, OthelloVentures commented on enyo-app/index.html
> +					console.log("user is trying to scroll down without anywhere to scroll to. Canceling propagation.");
As above

2022-11-16 19:17 UTC, OthelloVentures commented on enyo-app/index.html
> +					console.log("user is trying to scroll up without anywhere to scroll to. Canceling propagation.");
As above

2022-12-07 18:04 UTC, codepoet80 commented
I don't know how to revise a PR to make those changes, so I'll close this PR and submit a new one with some other modifications we're making for newer LuneOS support.

2022-12-07 18:04 UTC, closed without merging